package com.artplusplus.contpp.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.artplusplus.contpp.model.Empleado;
import com.artplusplus.contpp.repository.EmpleadoRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path="/empleado") // This means URL's start with /empleado (after Application path)
public class EmpleadoController {
    @Autowired // This means to get the bean called EmpleadoRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private EmpleadoRepository empleadoRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public ResponseEntity<Empleado> add(@RequestBody Empleado empleado) {
        // @ResponseBody means the returned Entity is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        Empleado newEmpleado = empleadoRepository.save(empleado);
        return ResponseEntity.ok(newEmpleado);
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Empleado> all() {
        // This returns a JSON or XML with the users
        return empleadoRepository.findAll();
    }

    @DeleteMapping(path="/{id}")
    public ResponseEntity<String> delete(@PathVariable String id) {
        Long empleadoId = Long.parseLong(id);
        if(empleadoRepository.existsById(empleadoId)){
            empleadoRepository.deleteById(empleadoId);
            return ResponseEntity.ok("Deleted");
        }
        return ResponseEntity.ok("ID not found");
    }
}
