package com.artplusplus.contpp;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/empleado") // This means URL's start with /empleado (after Application path)
public class EmpleadoController {
    @Autowired // This means to get the bean called EmpleadoRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private EmpleadoRepository empleadoRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String add(@RequestParam String name) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Empleado empleado = new Empleado();
        empleado.setName(name);
        empleadoRepository.save(empleado);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Empleado> all() {
        // This returns a JSON or XML with the users
        return empleadoRepository.findAll();
    }
}
